title: "Eric Opoku"
author: "Opoku Eric"
description: "University of Toronto"
#email: eric.opoku@mail.utoronto.ca
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

#How to add stuff in jekyll: https://github.com/jekyll/minima/blob/master/_config.yml
#YouTube: https://www.youtube.com/watch?v=qZsgPgGdOzQ

# Layout
show_social: true        # show site description and social links in the footer
show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home", icon: home}
  - {file: "README.md", title: "About me", icon: address-card}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:eric.opoku@mail.utoronto.ca"}
  - {title: Github, icon: github, url: "https://github.com/opokueric"}
#   - {title: YouTube, icon: YouTube logo, url: "https://www.youtube.com/@EricTheHealthEconomist"}
 
 #Generate social links in footer.
 social_links:
 - { platform: linkedin,       user_url: "https://www.linkedin.com/in/eric-opoku-m-a-mphil-63b450a5" }
#  - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #  - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #  - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #  - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  #  - { platform: gitlab,         user_url: "https://gitlab.com/jekyll" }
  #  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #  - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #  - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #  - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #  - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #  - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #  - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #  - { platform: x,              user_url: "https://x.com/jekyllrb" }
    - { platform: youtube,        user_url: "https://www.youtube.com/@EricTheHealthEconomist" }
  #  - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

 
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
