title: "Eric Opoku"
#author: "Eric Opoku"


# Site Author

author:
  name             : "Eric Opoku"
  avatar           : # "Headshot_202105.jpg"
  bio              : "I am an Assistant Professor of Health Economics at the University of Toronto's IHPME. My research focuses on the role of information in health care, including how consumers learn about their health risks and how providers value innovations in health care."
  location         :
  employer         : "University of Toronto, ON, Canada"
  googlescholar    : #"https://scholar.google.com/citations?user=Ks-_ZlIAAAAJ&hl=en"
  email            : "eric.opoku@mail.utoronto.ca"
  researchgate     :  # example: "https://www.researchgate.net/profile/yourprofile"
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "opokueric"
  google_plus      :
  keybase          :
  instagram        :
  lastfm           :
  linkedin         :
  orcid            : #"https://orcid.org/my-orcid?orcid=0000-0001-6947-3445"
  pinterest        :
  soundcloud       :
  stackoverflow    : # http://stackoverflow.com/users/123456/username
  steam            :
  tumblr           :
  twitter          : #"@Hoagland_Alex"
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :



description: "University of Toronto"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "archive.html", sidebaricon: home}
  - {file: "README.md", sidebaricon: address-card}
  - {title:"Team", file: "page3.md"}
  - {title:"Publications", file: "page4.md"}
  - {title:"Teaching and Talks", file: "page5.md"}
  - {title:"CV", file: "page6.md"}
  - {title:"Contact", file: "page7.md"}

 
external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:author@example.com"}
  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
