title: "Health Economics and Outcomes Research Network"
author: "Eric Opoku"
description: "University of Toronto"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {title:"Team", file: "page3.md"}
  - {title:"Publications", file: "page4.md"}
  - {title:"Teaching", file: "page5.md"}
  - {title:"Events", file: "page6.md"}
  - {title:"Resources", file: "resources.html"}
  - {title:"Health Innovations", file: "innovandres.md"}
  - {title:"Contact", file: "page7.md"}

#  - {title:"Health Innovation", file: "healthinnov.md.md", sidebaricon: address-card}
  #- {file: "codeanddata.html", sidebaricon: home}
 
external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:eric.opoku@mail.utoronto.ca"}
  - {title: Github, icon: github, url: "https://github.com/opokueric/opokueric.github.io"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/eric-opoku-m-a-mphil-63b450a5/"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
